spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: order-service-group

  application:
    name: order-service

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

payment-service:
  base-url: http://payment-service:8081

order-paid-topic: orders.events
delivery-assigned-topic: delivery.events